table member_dimension
	lineageTag: 048861f4-9cb3-4eb2-9fbf-f9fdf63bcad4

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: ed93cf75-5a32-4cce-9b58-5d369bc43d82
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 54515951-cde9-48fc-b3ac-1248f6628fcf
		summarizeBy: none
		sourceColumn: start_date

		variation Variation
			isDefault
			relationship: 433b39a3-1ecf-437e-b6ed-5bb080d349c4
			defaultHierarchy: LocalDateTable_afaaa39f-5bcd-411a-bd53-6fc18b4dad5c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d94fa72-786a-446b-9b1b-128567621dba
		summarizeBy: none
		sourceColumn: end_date

		variation Variation
			isDefault
			relationship: d3fffff5-2f50-4a23-9302-2bd543c9b26d
			defaultHierarchy: LocalDateTable_8d0018fc-096b-4d8d-b027-5ccdf2accc22.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column status
		dataType: string
		lineageTag: 23b61ebd-55f4-4b6e-b9c0-9219846043e7
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column terms_and_conditions_acceptance_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 255c16f5-198e-4f0c-8c2b-babf1728b32f
		summarizeBy: none
		sourceColumn: terms_and_conditions_acceptance_date

		variation Variation
			isDefault
			relationship: 6aa241f6-02d6-47c5-bae6-8c7baeb5ba4d
			defaultHierarchy: LocalDateTable_1fbc13d7-5f96-4b13-9db4-4d7d8fd70c5e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column screenname
		dataType: string
		lineageTag: 216c0aec-87b2-47cb-b8c7-739710d1fa11
		summarizeBy: none
		sourceColumn: screenname

		annotation SummarizationSetBy = Automatic

	column date_of_birth
		dataType: dateTime
		formatString: Long Date
		lineageTag: c8e3be1b-deac-4baf-98b3-d906de02edc4
		summarizeBy: none
		sourceColumn: date_of_birth

		variation Variation
			isDefault
			relationship: 1a4dda3e-6d78-4290-b52b-0b63e46c00b2
			defaultHierarchy: LocalDateTable_e1584295-9266-4b09-933b-5d51ab860adc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column join_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: eb431ffc-9674-4a84-b5de-6477770d2c3d
		summarizeBy: none
		sourceColumn: join_date

		variation Variation
			isDefault
			relationship: 05fbbc60-2b38-4aa6-8bb7-4c24d758a951
			defaultHierarchy: LocalDateTable_3cdf5e00-9928-402b-9fa1-7325f10bbd41.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column efid
		dataType: string
		lineageTag: 5a747584-78ac-4875-a95d-648c31ddb0d6
		summarizeBy: none
		sourceColumn: efid

		annotation SummarizationSetBy = Automatic

	column vendor_id
		dataType: string
		lineageTag: f4f874e2-27ee-4f70-9b50-2d25740b479a
		summarizeBy: none
		sourceColumn: vendor_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: a83547f2-3022-4e99-a60c-06fcad8eb2b9
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: bd4c5aab-3a1d-4121-8d39-050ec656375e
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column mobile_phone_number
		dataType: string
		lineageTag: 47dfda1a-d685-4da4-ae7f-bc3b267625b6
		summarizeBy: none
		sourceColumn: mobile_phone_number

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 22fba6c4-0142-4474-b543-ee3a0699e827
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column org_id
		dataType: int64
		formatString: 0
		lineageTag: 056e792a-1c86-4d92-94d7-fd45cb9d5a2c
		summarizeBy: sum
		sourceColumn: org_id

		annotation SummarizationSetBy = Automatic

	column middle_name
		dataType: string
		lineageTag: 62c9d931-4bb4-4eb2-89c8-0c27cbe18df8
		summarizeBy: none
		sourceColumn: middle_name

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 4db2ff17-5ecb-47e7-b920-0c1e24f59abd
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column division_name
		dataType: string
		lineageTag: cd08a321-0868-4e11-8fef-e50ce62864ee
		summarizeBy: none
		sourceColumn: division_name

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: 4434acc2-730c-49c3-a6ba-46ad04c08743
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column source_system_code
		dataType: string
		lineageTag: 33b8e950-a40f-4d5a-92ac-7ec049c1e464
		summarizeBy: none
		sourceColumn: source_system_code

		annotation SummarizationSetBy = Automatic

	column funding_arrangement_code
		dataType: string
		lineageTag: 5e0a2189-ab03-4ae2-a511-0cf019de0b32
		summarizeBy: none
		sourceColumn: funding_arrangement_code

		annotation SummarizationSetBy = Automatic

	column health_plan_product_code
		dataType: string
		lineageTag: c2c8ce89-a71c-4b1b-9c96-cba0cc6f0df0
		summarizeBy: none
		sourceColumn: health_plan_product_code

		annotation SummarizationSetBy = Automatic

	column legal_entity_code
		dataType: string
		lineageTag: bae77f2e-dd1f-420a-b801-ec0c0bacad7c
		summarizeBy: none
		sourceColumn: legal_entity_code

		annotation SummarizationSetBy = Automatic

	column line_of_business
		dataType: string
		lineageTag: 0182feab-cc5d-4fec-83ef-c39ffcb33a62
		summarizeBy: none
		sourceColumn: line_of_business

		annotation SummarizationSetBy = Automatic

	column member_effective_date
		dataType: string
		lineageTag: f4a16750-f297-431f-bab1-0f148828317d
		summarizeBy: none
		sourceColumn: member_effective_date

		annotation SummarizationSetBy = Automatic

	column member_termination_date
		dataType: string
		lineageTag: 23e2163d-ab09-4ccb-bacd-69ea1e8f01a9
		summarizeBy: none
		sourceColumn: member_termination_date

		annotation SummarizationSetBy = Automatic

	column medical_coverage
		dataType: string
		lineageTag: a902b7d2-7670-464d-b0ae-602c001124ab
		summarizeBy: none
		sourceColumn: medical_coverage

		annotation SummarizationSetBy = Automatic

	column medical_plan_organization_id
		dataType: string
		lineageTag: fd483cc1-4144-446d-a885-8220d93f6362
		summarizeBy: none
		sourceColumn: medical_plan_organization_id

		annotation SummarizationSetBy = Automatic

	column market_segment_name
		dataType: string
		lineageTag: a2f50cf6-4c21-4007-9d37-261b1c1f1180
		summarizeBy: none
		sourceColumn: market_segment_name

		annotation SummarizationSetBy = Automatic

	column marital_status
		dataType: string
		lineageTag: 52e5b7ca-e5fb-4eac-a073-e5e0fe512af5
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column group_policy_number
		dataType: string
		lineageTag: 3147d524-ebf8-4db1-8b2d-8f4205e3d3b6
		summarizeBy: none
		sourceColumn: group_policy_number

		annotation SummarizationSetBy = Automatic

	column purchaser_code
		dataType: string
		lineageTag: 97de2871-19d2-400f-8541-7f678da77604
		summarizeBy: none
		sourceColumn: purchaser_code

		annotation SummarizationSetBy = Automatic

	column plan_variation_and_branch_reporting_code
		dataType: string
		lineageTag: 638bd5b8-220d-47a5-b11f-b94b5803f8d5
		summarizeBy: none
		sourceColumn: plan_variation_and_branch_reporting_code

		annotation SummarizationSetBy = Automatic

	column retirement_plan_text
		dataType: string
		lineageTag: 2ebf5378-8843-43f5-badd-329f56940e36
		summarizeBy: none
		sourceColumn: retirement_plan_text

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 6d3b8f18-ab0f-4547-a977-543d64d74b6b
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column union_status
		dataType: string
		lineageTag: 2739a506-9217-4585-b198-790e881a857d
		summarizeBy: none
		sourceColumn: union_status

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: d3d2a7af-a6a2-4a92-aa4d-3c0ccb0f334f
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column work_location_name
		dataType: string
		lineageTag: e2b956e9-1831-4902-b7b2-8c00c679ee53
		summarizeBy: none
		sourceColumn: work_location_name

		annotation SummarizationSetBy = Automatic

	column population_id
		dataType: string
		lineageTag: 5676374e-692d-49ec-b38c-a4cdcb62b000
		summarizeBy: none
		sourceColumn: population_id

		annotation SummarizationSetBy = Automatic

	column insurance_issuance_state_code
		dataType: string
		lineageTag: ed5c1ffa-4a6b-4c34-a411-26d578edc131
		summarizeBy: none
		sourceColumn: insurance_issuance_state_code

		annotation SummarizationSetBy = Automatic

	column partner_name
		dataType: string
		lineageTag: 9e03752f-c784-416d-bd00-02b3ea78d1db
		summarizeBy: none
		sourceColumn: partner_name

		annotation SummarizationSetBy = Automatic

	column relationship_code
		dataType: string
		lineageTag: 5124da18-47c3-4a56-b532-577ee4acfb7b
		summarizeBy: none
		sourceColumn: relationship_code

		annotation SummarizationSetBy = Automatic

	column spee_indicator
		dataType: string
		lineageTag: 145b6f80-006a-4743-a6c2-f7f548bffebe
		summarizeBy: none
		sourceColumn: spee_indicator

		annotation SummarizationSetBy = Automatic

	column partner_id
		dataType: string
		lineageTag: e7f7315b-f6c1-4f6b-9ba8-bfea29011823
		summarizeBy: none
		sourceColumn: partner_id

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: c392f482-8594-4b96-b24f-0b0024d1573c
		summarizeBy: none
		sourceColumn: postal_code

		annotation SummarizationSetBy = Automatic

	column employee_id
		dataType: string
		lineageTag: 83b55364-e708-4eb6-9719-ff9058897455
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column client
		dataType: string
		lineageTag: d8240075-d358-4aab-8de4-52b7d6369f15
		summarizeBy: none
		sourceColumn: client

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: string
		lineageTag: 03d7456b-9e6f-4354-a05e-502e1b7a6954
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column client_name
		dataType: string
		lineageTag: f9dafb0f-d94d-4040-9a7e-b66199df89c9
		summarizeBy: none
		sourceColumn: client_name

		annotation SummarizationSetBy = Automatic

	column affiliation_id
		dataType: string
		lineageTag: 846ae7c9-75fd-45f0-b126-e8a670e68aea
		summarizeBy: none
		sourceColumn: affiliation_id

		annotation SummarizationSetBy = Automatic

	column affiliation_description
		dataType: string
		lineageTag: 56968849-abed-43c1-a027-2abc0005128d
		summarizeBy: none
		sourceColumn: affiliation_description

		annotation SummarizationSetBy = Automatic

	column address_line_1
		dataType: string
		lineageTag: f074bfce-795b-4d42-955a-ee0b4625777e
		summarizeBy: none
		sourceColumn: address_line_1

		annotation SummarizationSetBy = Automatic

	column address_line_2
		dataType: string
		lineageTag: 863607db-74ba-4a56-a970-9166e6dbffb7
		summarizeBy: none
		sourceColumn: address_line_2

		annotation SummarizationSetBy = Automatic

	column alternate_id
		dataType: string
		lineageTag: 8d176939-e2c9-42d9-96fd-2f8101921235
		summarizeBy: none
		sourceColumn: alternate_id

		annotation SummarizationSetBy = Automatic

	column cobra_text
		dataType: string
		lineageTag: 834e3193-a989-4f24-aa70-3417d0d9042d
		summarizeBy: none
		sourceColumn: cobra_text

		annotation SummarizationSetBy = Automatic

	column salary_hourly_indicator
		dataType: string
		lineageTag: ceec4218-e7d7-411d-8e01-44fc3d04cde2
		summarizeBy: none
		sourceColumn: salary_hourly_indicator

		annotation SummarizationSetBy = Automatic

	column new_hire_indicator
		dataType: string
		lineageTag: 6394416e-2fc7-43b0-9073-5767f58c50d3
		summarizeBy: none
		sourceColumn: new_hire_indicator

		annotation SummarizationSetBy = Automatic

	column hire_date
		dataType: string
		lineageTag: cd66d57f-0579-416f-9493-988fafd1e40a
		summarizeBy: none
		sourceColumn: hire_date

		annotation SummarizationSetBy = Automatic

	column option_id
		dataType: string
		lineageTag: 7d6d27b3-bcd1-43a1-b1ae-4fd738607699
		summarizeBy: none
		sourceColumn: option_id

		annotation SummarizationSetBy = Automatic

	column incentive_indicator
		dataType: string
		lineageTag: 33e65805-29da-44a5-b0c6-afbd9b0ebe5a
		summarizeBy: none
		sourceColumn: incentive_indicator

		annotation SummarizationSetBy = Automatic

	column group_code
		dataType: string
		lineageTag: d3aa347a-1608-4db0-9917-6d4c11f00c16
		summarizeBy: none
		sourceColumn: group_code

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_1
		dataType: string
		lineageTag: 1642c60c-3f02-4966-8f7c-7dfe71388cef
		summarizeBy: none
		sourceColumn: custom_defined_field_1

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_2
		dataType: string
		lineageTag: 620c5cba-960a-40e8-af1e-db7d240ddec0
		summarizeBy: none
		sourceColumn: custom_defined_field_2

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_3
		dataType: string
		lineageTag: 6ae15829-c085-48e9-a687-be47cf3c1902
		summarizeBy: none
		sourceColumn: custom_defined_field_3

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_4
		dataType: string
		lineageTag: 37a9a08b-211f-4b65-8be2-17bba214947f
		summarizeBy: none
		sourceColumn: custom_defined_field_4

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_5
		dataType: string
		lineageTag: cf270fe9-a736-4289-8152-e06c907e7162
		summarizeBy: none
		sourceColumn: custom_defined_field_5

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_6
		dataType: string
		lineageTag: b942ae36-ff33-4a6e-b9e6-3ebc2a304074
		summarizeBy: none
		sourceColumn: custom_defined_field_6

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_7
		dataType: string
		lineageTag: 1672837c-eb0b-4972-a4b5-d3b812acbfb0
		summarizeBy: none
		sourceColumn: custom_defined_field_7

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_8
		dataType: string
		lineageTag: 6edae94b-bb9c-4eab-b0c2-d09adadaccc7
		summarizeBy: none
		sourceColumn: custom_defined_field_8

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_9
		dataType: string
		lineageTag: c47e61f2-00eb-4d5e-b720-bc3aa6f67b86
		summarizeBy: none
		sourceColumn: custom_defined_field_9

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_10
		dataType: string
		lineageTag: f3b254ec-aca6-4ccf-b98a-91e3ab9d259b
		summarizeBy: none
		sourceColumn: custom_defined_field_10

		annotation SummarizationSetBy = Automatic

	column suffix
		dataType: string
		lineageTag: 10b3ec8c-5af5-4c6e-82d4-745445e65c3e
		summarizeBy: none
		sourceColumn: suffix

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: e7ad4201-86e4-49fe-b014-e17407b69bde
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column latest_date
		dataType: string
		lineageTag: 0ef136e1-1aea-4eaf-982f-939b29e3f0ad
		summarizeBy: none
		sourceColumn: latest_date

		annotation SummarizationSetBy = Automatic

	column Client_id_name
		dataType: string
		lineageTag: 3039d56d-fa6d-42be-af78-ca9404350208
		summarizeBy: none
		sourceColumn: Client_id_name

		annotation SummarizationSetBy = Automatic

	partition member_dimension = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("capillary-notebook-ushc.cloud.databricks.com", "sql/protocolv1/o/3729305870030/0813-073652-brrb0l8n", null),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    optum_dev_Schema = hive_metastore_Database{[Name=SchemaName,Kind="Schema"]}[Data],
				    member_dimension_Table = optum_dev_Schema{[Name="member_dimension",Kind="Table"]}[Data],
				    #"Added Custom" = Table.AddColumn(member_dimension_Table, "Client_id_name", each if [client_name] = null or [client_name] = "" then [client_id] else [client_id] & " " & [client_name]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"terms_and_conditions_acceptance_date", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"terms_and_conditions_acceptance_date", type date}, {"join_date", type datetime}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"join_date", type date}, {"start_date", type date}, {"end_date", type date}, {"date_of_birth", type datetime}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Changed Type2",{{"date_of_birth", type date}})
				in
				    #"Changed Type3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

