table member_dimension
	lineageTag: 142eea0d-c2e3-498f-b76e-0711cbf2939d

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: 93b8be93-d57a-403d-a1f8-2d0b685009dc
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: string
		lineageTag: a1b2d5ba-d467-41db-8096-b46aafce037e
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: string
		lineageTag: 2826ae7d-4fa9-4bc0-8a38-f108e9b9747a
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: e7ca2251-236b-4356-9f4f-7f522a57abb5
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column terms_and_conditions_acceptance_date
		dataType: string
		lineageTag: f6433c92-e8ee-482f-9bce-bb67ed6033d3
		summarizeBy: none
		sourceColumn: terms_and_conditions_acceptance_date

		annotation SummarizationSetBy = Automatic

	column screenname
		dataType: string
		lineageTag: 733b0fa2-bf9a-49a6-a213-1e3cebd5d2e4
		summarizeBy: none
		sourceColumn: screenname

		annotation SummarizationSetBy = Automatic

	column date_of_birth
		dataType: string
		lineageTag: 98737632-f072-48b3-a950-2bba8a4a0193
		summarizeBy: none
		sourceColumn: date_of_birth

		annotation SummarizationSetBy = Automatic

	column join_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: df2bff6b-71dc-42fe-9c24-6a436c7dc120
		summarizeBy: none
		sourceColumn: join_date

		variation Variation
			isDefault
			relationship: d3368556-f1f1-4e1a-b676-c18e8f6f9dae
			defaultHierarchy: LocalDateTable_03a0033c-0419-4543-969f-2a44b7d4f294.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column efid
		dataType: string
		lineageTag: cab5b19d-2fae-423c-9558-dbcceb5920ff
		summarizeBy: none
		sourceColumn: efid

		annotation SummarizationSetBy = Automatic

	column vendor_id
		dataType: string
		lineageTag: 6167c3d1-63be-4648-a705-f1c05a59bad5
		summarizeBy: none
		sourceColumn: vendor_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: acd00b2d-b6fc-4b00-b377-99a9252790ef
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 1a2e58ba-846e-4336-bcae-ac91a5f3a4af
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column mobile_phone_number
		dataType: string
		lineageTag: f6ef2172-4611-48d2-8e92-fd6bb4ebc6ce
		summarizeBy: none
		sourceColumn: mobile_phone_number

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 60c04a0f-45d3-43b5-ab0d-8421b227d4a5
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column middle_name
		dataType: string
		lineageTag: 6a42f556-4635-4ba6-8d50-3baaba16adac
		summarizeBy: none
		sourceColumn: middle_name

		annotation SummarizationSetBy = Automatic

	column division_name
		dataType: string
		lineageTag: 62b0daee-4204-420a-97b8-1a1bfe32fe93
		summarizeBy: none
		sourceColumn: division_name

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: 6c982b85-2162-4bc8-8c30-84bbd3a87626
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column source_system_code
		dataType: string
		lineageTag: c4adf2a5-318d-4639-9edf-c5700ed0d77c
		summarizeBy: none
		sourceColumn: source_system_code

		annotation SummarizationSetBy = Automatic

	column funding_arrangement_code
		dataType: string
		lineageTag: cb7960bb-63cb-4eda-8927-8b7f5f04870e
		summarizeBy: none
		sourceColumn: funding_arrangement_code

		annotation SummarizationSetBy = Automatic

	column health_plan_product_code
		dataType: string
		lineageTag: f06bc3e3-304e-4cc3-bc31-9d00bc3e90e7
		summarizeBy: none
		sourceColumn: health_plan_product_code

		annotation SummarizationSetBy = Automatic

	column legal_entity_code
		dataType: string
		lineageTag: 2b903ff6-3206-40aa-b5b0-62d3de3bf014
		summarizeBy: none
		sourceColumn: legal_entity_code

		annotation SummarizationSetBy = Automatic

	column line_of_business
		dataType: string
		lineageTag: 152b87c6-7195-4eab-b113-cfd4b1607fdb
		summarizeBy: none
		sourceColumn: line_of_business

		annotation SummarizationSetBy = Automatic

	column member_effective_date
		dataType: string
		lineageTag: 42445a68-e299-4e67-8b84-764c6089b57f
		summarizeBy: none
		sourceColumn: member_effective_date

		annotation SummarizationSetBy = Automatic

	column member_termination_date
		dataType: string
		lineageTag: 11b46eab-3a10-4a2a-bcca-8e9e21e427dd
		summarizeBy: none
		sourceColumn: member_termination_date

		annotation SummarizationSetBy = Automatic

	column medical_coverage
		dataType: string
		lineageTag: 07cd7913-81d7-4557-a090-e8f87d85ba6a
		summarizeBy: none
		sourceColumn: medical_coverage

		annotation SummarizationSetBy = Automatic

	column medical_plan_organization_id
		dataType: string
		lineageTag: ada02f56-c676-4282-ae14-adf78b6ee6b9
		summarizeBy: none
		sourceColumn: medical_plan_organization_id

		annotation SummarizationSetBy = Automatic

	column market_segment_name
		dataType: string
		lineageTag: 5427d301-d391-4da9-8a89-8dcd7a329c88
		summarizeBy: none
		sourceColumn: market_segment_name

		annotation SummarizationSetBy = Automatic

	column marital_status
		dataType: string
		lineageTag: 13c3033a-43eb-4f56-9a7b-c2947ec9666c
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column group_policy_number
		dataType: string
		lineageTag: 8dd141f8-2e74-49eb-ba7b-baa63053de51
		summarizeBy: none
		sourceColumn: group_policy_number

		annotation SummarizationSetBy = Automatic

	column purchaser_code
		dataType: string
		lineageTag: 64d72c6d-4bcb-480a-8c1a-7f9885de4803
		summarizeBy: none
		sourceColumn: purchaser_code

		annotation SummarizationSetBy = Automatic

	column plan_variation_and_branch_reporting_code
		dataType: string
		lineageTag: 86a516b3-6d99-4e77-a78c-af8e9ddb16fe
		summarizeBy: none
		sourceColumn: plan_variation_and_branch_reporting_code

		annotation SummarizationSetBy = Automatic

	column retirement_plan_text
		dataType: string
		lineageTag: f9acfe19-0a02-4fc8-b596-7182c8c3cbc1
		summarizeBy: none
		sourceColumn: retirement_plan_text

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 696db820-f9ea-4348-abdb-a08ca449f663
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column union_status
		dataType: string
		lineageTag: f3f1ff85-9526-4a07-a681-8da265bd3981
		summarizeBy: none
		sourceColumn: union_status

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 470393cc-998b-4e58-b5e0-94712d77d828
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column work_location_name
		dataType: string
		lineageTag: 1065a704-f848-4a9f-b3c6-dbaf31f47d4d
		summarizeBy: none
		sourceColumn: work_location_name

		annotation SummarizationSetBy = Automatic

	column population_id
		dataType: string
		lineageTag: a86a1671-62e7-49d3-a490-69465426e27b
		summarizeBy: none
		sourceColumn: population_id

		annotation SummarizationSetBy = Automatic

	column insurance_issuance_state_code
		dataType: string
		lineageTag: 2d40f6fd-59a8-4ea7-ad42-53b1e6dcdd57
		summarizeBy: none
		sourceColumn: insurance_issuance_state_code

		annotation SummarizationSetBy = Automatic

	column partner_name
		dataType: string
		lineageTag: 71322b3d-1db0-4d4b-b1c0-26ac8400548b
		summarizeBy: none
		sourceColumn: partner_name

		annotation SummarizationSetBy = Automatic

	column relationship_code
		dataType: string
		lineageTag: 177a8752-c813-47f0-b06a-21428ec8002e
		summarizeBy: none
		sourceColumn: relationship_code

		annotation SummarizationSetBy = Automatic

	column spee_indicator
		dataType: string
		lineageTag: 885ddf9c-7c93-4a51-86e2-0a93b6481768
		summarizeBy: none
		sourceColumn: spee_indicator

		annotation SummarizationSetBy = Automatic

	column partner_id
		dataType: string
		lineageTag: a9b78fc6-a7cc-4350-b47a-dcccb98d273c
		summarizeBy: none
		sourceColumn: partner_id

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: a14f5462-7d3e-45b8-bbb9-b1c9312f3e12
		summarizeBy: none
		sourceColumn: postal_code

		annotation SummarizationSetBy = Automatic

	column employee_id
		dataType: string
		lineageTag: 0ca0e5bf-52d2-443f-82bb-27ebf946098d
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column client
		dataType: string
		lineageTag: 70ead6f4-f47f-4e78-80bb-22fea7be3e8c
		summarizeBy: none
		sourceColumn: client

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: string
		lineageTag: e6e5bef3-fcc9-4f15-982b-46c0fc7eddec
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column client_name
		dataType: string
		lineageTag: 90d0da32-fa83-4b49-909b-09281cf1ab39
		summarizeBy: none
		sourceColumn: client_name

		annotation SummarizationSetBy = Automatic

	column affiliation_id
		dataType: string
		lineageTag: 8fffac18-af98-496d-a5d9-226e063c25ac
		summarizeBy: none
		sourceColumn: affiliation_id

		annotation SummarizationSetBy = Automatic

	column affiliation_description
		dataType: string
		lineageTag: 0f99338b-cd4f-4fff-a2e9-057fd7f1d62a
		summarizeBy: none
		sourceColumn: affiliation_description

		annotation SummarizationSetBy = Automatic

	column address_line_1
		dataType: string
		lineageTag: 7b0525eb-6d95-449e-9029-81c981ec342a
		summarizeBy: none
		sourceColumn: address_line_1

		annotation SummarizationSetBy = Automatic

	column address_line_2
		dataType: string
		lineageTag: 1efca460-ae66-4124-ad29-6c4da730200a
		summarizeBy: none
		sourceColumn: address_line_2

		annotation SummarizationSetBy = Automatic

	column alternate_id
		dataType: string
		lineageTag: acd175eb-7593-42e9-b82d-293426b86947
		summarizeBy: none
		sourceColumn: alternate_id

		annotation SummarizationSetBy = Automatic

	column cobra_text
		dataType: string
		lineageTag: e04d753a-2d8e-44e9-892a-0b496bb4aac7
		summarizeBy: none
		sourceColumn: cobra_text

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 00090bcd-3861-4d55-bcd8-6a7535f6284f
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column salary_hourly_indicator
		dataType: string
		lineageTag: 92a3075b-b5a8-4402-bbd4-d752d5230b15
		summarizeBy: none
		sourceColumn: salary_hourly_indicator

		annotation SummarizationSetBy = Automatic

	column new_hire_indicator
		dataType: string
		lineageTag: 5e7e7fcd-36f0-4116-af44-f8ec86858905
		summarizeBy: none
		sourceColumn: new_hire_indicator

		annotation SummarizationSetBy = Automatic

	column hire_date
		dataType: string
		lineageTag: f3058a47-7e08-47a5-b661-624b81ffffa4
		summarizeBy: none
		sourceColumn: hire_date

		annotation SummarizationSetBy = Automatic

	column option_id
		dataType: string
		lineageTag: 813229ad-6583-4034-9bae-bcc52afa5508
		summarizeBy: none
		sourceColumn: option_id

		annotation SummarizationSetBy = Automatic

	column incentive_indicator
		dataType: string
		lineageTag: 6b2ebed7-3ad9-4590-87c0-b0f081b0bc53
		summarizeBy: none
		sourceColumn: incentive_indicator

		annotation SummarizationSetBy = Automatic

	column group_code
		dataType: string
		lineageTag: 189d4910-9597-407f-b075-3ef05ce40e53
		summarizeBy: none
		sourceColumn: group_code

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_1
		dataType: string
		lineageTag: 4cb5318c-45d7-44c1-bcad-3bbf29ff5a65
		summarizeBy: none
		sourceColumn: custom_defined_field_1

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_2
		dataType: string
		lineageTag: a0d06d0d-b8ff-430a-b608-6d6172393849
		summarizeBy: none
		sourceColumn: custom_defined_field_2

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_3
		dataType: string
		lineageTag: 57788dc8-569a-4f9b-aa25-ae1e9514e059
		summarizeBy: none
		sourceColumn: custom_defined_field_3

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_4
		dataType: string
		lineageTag: 58d97b5d-e76e-48e4-84bb-a861a4df3a07
		summarizeBy: none
		sourceColumn: custom_defined_field_4

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_5
		dataType: string
		lineageTag: 8dc136fb-c44b-4600-a51d-01e9e9938141
		summarizeBy: none
		sourceColumn: custom_defined_field_5

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_6
		dataType: string
		lineageTag: a77bdf42-d4b4-4d2e-9077-bd4f3d1da851
		summarizeBy: none
		sourceColumn: custom_defined_field_6

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_7
		dataType: string
		lineageTag: d430bca7-6d83-4a6b-82bd-45d07f4f9bd0
		summarizeBy: none
		sourceColumn: custom_defined_field_7

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_8
		dataType: string
		lineageTag: b2f89dd6-3d78-4f14-8dea-355288cabcdc
		summarizeBy: none
		sourceColumn: custom_defined_field_8

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_9
		dataType: string
		lineageTag: cbc11c99-c3c8-41b8-8323-5f42a97e0468
		summarizeBy: none
		sourceColumn: custom_defined_field_9

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_10
		dataType: string
		lineageTag: a0697ee7-121e-48ff-9f72-7c7660494408
		summarizeBy: none
		sourceColumn: custom_defined_field_10

		annotation SummarizationSetBy = Automatic

	column suffix
		dataType: string
		lineageTag: 263f9ab8-0023-4a84-bd78-1dfeece5bdb4
		summarizeBy: none
		sourceColumn: suffix

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: bb0c5b24-acde-4cc3-b6bd-447238dc905d
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column latest_date
		dataType: string
		lineageTag: d62cf9ee-3091-4271-8454-e475d760a169
		summarizeBy: none
		sourceColumn: latest_date

		annotation SummarizationSetBy = Automatic

	column org_id
		dataType: int64
		formatString: 0
		lineageTag: a8f4298b-2e63-4e0f-9d74-44dfa7c85cbe
		summarizeBy: sum
		sourceColumn: org_id

		annotation SummarizationSetBy = Automatic

	column Client_id_name
		dataType: string
		lineageTag: 4ad9f51f-3067-41dd-afb0-5374263f3d73
		summarizeBy: none
		sourceColumn: Client_id_name

		annotation SummarizationSetBy = Automatic

	partition member_dimension = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("capillary-notebook-ushc.cloud.databricks.com", "sql/protocolv1/o/3729305870030/0813-073652-brrb0l8n", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    optum_dev_Schema = hive_metastore_Database{[Name=SchemaName,Kind="Schema"]}[Data],
				    member_dimension_Table = optum_dev_Schema{[Name="member_dimension",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(member_dimension_Table,{{"join_date", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"join_date", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Client_id_name", each if [client_name] = null or [client_name] = "" then [client_id] else [client_id] & " " & [client_name])
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

