table mission_dimension
	lineageTag: b8274bb0-bd97-4d89-997b-fda31ab15c6a

	column mission_id
		dataType: int64
		formatString: 0
		lineageTag: a61249d8-1d40-4f5a-bb06-187c219766a2
		summarizeBy: none
		sourceColumn: mission_id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: e6da2df6-0677-4214-8ba9-c35725832cc4
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column categories
		dataType: string
		lineageTag: 9a05b035-3f22-4e01-97a6-7f81b57fa2b6
		summarizeBy: none
		sourceColumn: categories

		annotation SummarizationSetBy = Automatic

	column overview
		dataType: string
		lineageTag: b5d9cab8-dde7-4342-be07-ecc029264c2f
		summarizeBy: none
		sourceColumn: overview

		annotation SummarizationSetBy = Automatic

	column effort_intensity
		dataType: string
		lineageTag: 757e7e98-b52f-45aa-af74-adcb08f781f1
		summarizeBy: none
		sourceColumn: effort_intensity

		annotation SummarizationSetBy = Automatic

	column target_amount
		dataType: int64
		formatString: 0
		lineageTag: a329e794-2d85-4cfa-b48b-2cfc8b40a2de
		summarizeBy: sum
		sourceColumn: target_amount

		annotation SummarizationSetBy = Automatic

	column frequency_interval_amount
		dataType: int64
		formatString: 0
		lineageTag: 89d8f4ec-6aeb-4660-a2bb-8e75a07f88bc
		summarizeBy: sum
		sourceColumn: frequency_interval_amount

		annotation SummarizationSetBy = Automatic

	column duration_interval_amount
		dataType: int64
		formatString: 0
		lineageTag: 2b305e24-7ef3-4d7e-bf14-56ac99f15b4f
		summarizeBy: sum
		sourceColumn: duration_interval_amount

		annotation SummarizationSetBy = Automatic

	column duration_interval_type
		dataType: string
		lineageTag: 00902286-e932-49f3-9605-265054c963c1
		summarizeBy: none
		sourceColumn: duration_interval_type

		annotation SummarizationSetBy = Automatic

	column points_for_completing_a_day
		dataType: int64
		formatString: 0
		lineageTag: c38c67de-e93b-45b8-9331-b59a984c5f59
		summarizeBy: sum
		sourceColumn: points_for_completing_a_day

		annotation SummarizationSetBy = Automatic

	column points_for_completing_a_week
		dataType: int64
		formatString: 0
		lineageTag: 5990c070-c345-4f85-bc73-07b7b764f562
		summarizeBy: sum
		sourceColumn: points_for_completing_a_week

		annotation SummarizationSetBy = Automatic

	column points_for_completing_the_mission
		dataType: int64
		formatString: 0
		lineageTag: fa515196-fbe9-40c0-92e5-85022d02c435
		summarizeBy: sum
		sourceColumn: points_for_completing_the_mission

		annotation SummarizationSetBy = Automatic

	column clinical_mission
		dataType: int64
		formatString: 0
		lineageTag: febf1200-01e4-4b70-aa57-721359c0f5a9
		summarizeBy: sum
		sourceColumn: clinical_mission

		annotation SummarizationSetBy = Automatic

	column wellness_benefit_level
		dataType: string
		lineageTag: 426ae90d-3277-4c7f-bfba-7bc90d771894
		summarizeBy: none
		sourceColumn: wellness_benefit_level

		annotation SummarizationSetBy = Automatic

	column last_updated_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: bfd44c9a-20a6-4ad5-9bdf-d493070b8215
		summarizeBy: none
		sourceColumn: last_updated_date

		variation Variation
			isDefault
			relationship: fd34a605-2fbe-4cd8-aa33-76d57291151a
			defaultHierarchy: LocalDateTable_de2061d4-45d5-46a5-8eaf-0f50fad81cd9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition mission_dimension = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("capillary-notebook-ushc.cloud.databricks.com", "sql/protocolv1/o/3729305870030/0813-073652-brrb0l8n", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    optum_dev_Schema = hive_metastore_Database{[Name=SchemaName,Kind="Schema"]}[Data],
				    mission_dimension_Table = optum_dev_Schema{[Name="mission_dimension",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(mission_dimension_Table,{{"mission_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

