table member_dimension
	lineageTag: afe86cfc-3058-4450-aae9-4da6bd306863

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: 8b7435e4-7334-4a00-93ab-73bd23c339e7
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6008927b-1289-40cd-9724-cfc821d140e4
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column end_date
		dataType: string
		lineageTag: 6fb9a798-3193-4c2e-92bb-f153b38a91ee
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: af0b34da-49f2-497d-a6e1-e15ecd24dc8c
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column terms_and_conditions_acceptance_date
		dataType: string
		lineageTag: 8e42826a-8790-4a52-9375-e30906983a68
		summarizeBy: none
		sourceColumn: terms_and_conditions_acceptance_date

		annotation SummarizationSetBy = Automatic

	column screenname
		dataType: string
		lineageTag: b8a9bcf8-86f6-4565-aa8e-e46d8813e10e
		summarizeBy: none
		sourceColumn: screenname

		annotation SummarizationSetBy = Automatic

	column date_of_birth
		dataType: string
		lineageTag: e3fa515a-c27d-4697-aff9-90e9cb860ab6
		summarizeBy: none
		sourceColumn: date_of_birth

		annotation SummarizationSetBy = Automatic

	column join_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6b14e35c-a027-4212-9349-549431abdb37
		summarizeBy: none
		sourceColumn: join_date

		variation Variation
			isDefault
			relationship: 0f30ab32-7346-49b6-b89a-d62a0942f664
			defaultHierarchy: LocalDateTable_7cb70b28-47f0-4e1c-9fa0-e23cf30b9fb2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column efid
		dataType: string
		lineageTag: ef756e1d-6e38-4893-b58c-174305e80a5b
		summarizeBy: none
		sourceColumn: efid

		annotation SummarizationSetBy = Automatic

	column vendor_id
		dataType: string
		lineageTag: 6712b063-5cc4-4ff8-ba7b-0a826eee90f9
		summarizeBy: none
		sourceColumn: vendor_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 912ec115-87ae-4dc0-882c-0b6fa2737fe6
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 23ffb990-17fa-427e-bf60-4e540b1bc3e3
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column mobile_phone_number
		dataType: string
		lineageTag: 60783347-0def-40cf-9992-126679a7a2fb
		summarizeBy: none
		sourceColumn: mobile_phone_number

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: e222e5b3-e123-45db-8ba6-2d8673565a72
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column middle_name
		dataType: string
		lineageTag: db7bfb18-8a93-4a15-b0db-61b91103af7d
		summarizeBy: none
		sourceColumn: middle_name

		annotation SummarizationSetBy = Automatic

	column division_name
		dataType: string
		lineageTag: 2e69cbfd-16a9-4f44-85f5-67dd38f4cbbe
		summarizeBy: none
		sourceColumn: division_name

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: 27aeed7c-8343-417f-a67c-d436227dbcd0
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column source_system_code
		dataType: string
		lineageTag: 22c7584b-def3-4a69-bb5f-4497bd1949bb
		summarizeBy: none
		sourceColumn: source_system_code

		annotation SummarizationSetBy = Automatic

	column funding_arrangement_code
		dataType: string
		lineageTag: a0f9b4ba-7a1f-4e09-a8a9-1f17092c9d93
		summarizeBy: none
		sourceColumn: funding_arrangement_code

		annotation SummarizationSetBy = Automatic

	column health_plan_product_code
		dataType: string
		lineageTag: f2b1dbe5-09bd-4d15-bbee-8a6f1f80b0ae
		summarizeBy: none
		sourceColumn: health_plan_product_code

		annotation SummarizationSetBy = Automatic

	column legal_entity_code
		dataType: string
		lineageTag: ddb059c0-060f-4e10-aea8-da607283bfcb
		summarizeBy: none
		sourceColumn: legal_entity_code

		annotation SummarizationSetBy = Automatic

	column line_of_business
		dataType: string
		lineageTag: afa9bd9c-edcf-47c6-9dba-02765ced4aab
		summarizeBy: none
		sourceColumn: line_of_business

		annotation SummarizationSetBy = Automatic

	column member_effective_date
		dataType: string
		lineageTag: 049d25ea-6a27-484d-bbe4-e83734b43936
		summarizeBy: none
		sourceColumn: member_effective_date

		annotation SummarizationSetBy = Automatic

	column member_termination_date
		dataType: string
		lineageTag: e194f828-9dbd-47a1-b853-80270cfd03fe
		summarizeBy: none
		sourceColumn: member_termination_date

		annotation SummarizationSetBy = Automatic

	column medical_coverage
		dataType: string
		lineageTag: 3b881067-c30f-4f1e-8a1e-4b30734800e0
		summarizeBy: none
		sourceColumn: medical_coverage

		annotation SummarizationSetBy = Automatic

	column medical_plan_organization_id
		dataType: string
		lineageTag: 0f664e29-708c-49b2-bf81-7fe240167622
		summarizeBy: none
		sourceColumn: medical_plan_organization_id

		annotation SummarizationSetBy = Automatic

	column market_segment_name
		dataType: string
		lineageTag: 5802792b-e54c-4103-b946-8eb8bdb0aacb
		summarizeBy: none
		sourceColumn: market_segment_name

		annotation SummarizationSetBy = Automatic

	column marital_status
		dataType: string
		lineageTag: d715539b-996a-49cb-8b5e-fe8365d51115
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column group_policy_number
		dataType: string
		lineageTag: e0ffabe9-78e1-4dcc-8124-f31ad8496c95
		summarizeBy: none
		sourceColumn: group_policy_number

		annotation SummarizationSetBy = Automatic

	column purchaser_code
		dataType: string
		lineageTag: a726d4ff-67dd-4310-a342-e34ebc94c657
		summarizeBy: none
		sourceColumn: purchaser_code

		annotation SummarizationSetBy = Automatic

	column plan_variation_and_branch_reporting_code
		dataType: string
		lineageTag: 501e6a72-7b05-410f-80a5-2234defb7871
		summarizeBy: none
		sourceColumn: plan_variation_and_branch_reporting_code

		annotation SummarizationSetBy = Automatic

	column retirement_plan_text
		dataType: string
		lineageTag: 677375b4-84d0-42c0-bfc4-257dfaa76bac
		summarizeBy: none
		sourceColumn: retirement_plan_text

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 0427061c-13ff-479d-9c5d-85f697626a5a
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column union_status
		dataType: string
		lineageTag: ede56707-da6e-412d-ac01-c1701b1dd19e
		summarizeBy: none
		sourceColumn: union_status

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 1e5df4a3-07e0-49dd-a2c8-b3c7ea058a85
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column work_location_name
		dataType: string
		lineageTag: 709ac72f-f24b-4b84-aac6-ef316ed60798
		summarizeBy: none
		sourceColumn: work_location_name

		annotation SummarizationSetBy = Automatic

	column population_id
		dataType: string
		lineageTag: 37835495-e435-43ea-af94-61043b4f3241
		summarizeBy: none
		sourceColumn: population_id

		annotation SummarizationSetBy = Automatic

	column insurance_issuance_state_code
		dataType: string
		lineageTag: b4c0a40c-034a-4843-8b60-9e94e54ad1cf
		summarizeBy: none
		sourceColumn: insurance_issuance_state_code

		annotation SummarizationSetBy = Automatic

	column partner_name
		dataType: string
		lineageTag: 3070964b-7b50-429b-b3fb-33d957cc1849
		summarizeBy: none
		sourceColumn: partner_name

		annotation SummarizationSetBy = Automatic

	column relationship_code
		dataType: string
		lineageTag: cf295c5d-ee26-48e1-88bc-aa4c96486758
		summarizeBy: none
		sourceColumn: relationship_code

		annotation SummarizationSetBy = Automatic

	column spee_indicator
		dataType: string
		lineageTag: 25877fbe-6514-45ac-9477-1457ffa8be08
		summarizeBy: none
		sourceColumn: spee_indicator

		annotation SummarizationSetBy = Automatic

	column partner_id
		dataType: string
		lineageTag: 6ea4e0b8-a551-408a-b67d-00ea535eea96
		summarizeBy: none
		sourceColumn: partner_id

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: 36ae3f1e-f89c-4a5b-aa07-51be341e5d88
		summarizeBy: none
		sourceColumn: postal_code

		annotation SummarizationSetBy = Automatic

	column employee_id
		dataType: string
		lineageTag: 5e69710a-9799-4a53-8ec0-0cb58ec2eaa3
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column client
		dataType: string
		lineageTag: ceaf6050-c03d-4169-8475-c4ea028c6a1b
		summarizeBy: none
		sourceColumn: client

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: string
		lineageTag: 2b320e2d-3b69-46e8-8f01-26a869302de6
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column client_name
		dataType: string
		lineageTag: 9dbaca98-32b0-441b-801f-1d865810b3d7
		summarizeBy: none
		sourceColumn: client_name

		annotation SummarizationSetBy = Automatic

	column affiliation_id
		dataType: string
		lineageTag: dde6f682-2ca7-4699-b818-65b83199c2b8
		summarizeBy: none
		sourceColumn: affiliation_id

		annotation SummarizationSetBy = Automatic

	column affiliation_description
		dataType: string
		lineageTag: cf355093-2c90-4e5e-83cb-086c04fbf1a4
		summarizeBy: none
		sourceColumn: affiliation_description

		annotation SummarizationSetBy = Automatic

	column address_line_1
		dataType: string
		lineageTag: c9d914a2-be14-4922-8c6b-2910bf217b08
		summarizeBy: none
		sourceColumn: address_line_1

		annotation SummarizationSetBy = Automatic

	column address_line_2
		dataType: string
		lineageTag: 287a2f43-4628-44a9-916b-bce00ca513b6
		summarizeBy: none
		sourceColumn: address_line_2

		annotation SummarizationSetBy = Automatic

	column alternate_id
		dataType: string
		lineageTag: 90eb60f7-a5fe-4757-b8e5-0aeea31071a8
		summarizeBy: none
		sourceColumn: alternate_id

		annotation SummarizationSetBy = Automatic

	column cobra_text
		dataType: string
		lineageTag: 5e6ec546-bfef-46da-8c39-2f0a143c65d3
		summarizeBy: none
		sourceColumn: cobra_text

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 1df40ddd-61fc-4baa-b28a-ea34d1ab86a1
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column salary_hourly_indicator
		dataType: string
		lineageTag: ce1d9b3e-8d08-4ddd-a233-50b427d4ebb4
		summarizeBy: none
		sourceColumn: salary_hourly_indicator

		annotation SummarizationSetBy = Automatic

	column new_hire_indicator
		dataType: string
		lineageTag: d6daa255-7e32-4280-8a3c-5db81ce4e9f8
		summarizeBy: none
		sourceColumn: new_hire_indicator

		annotation SummarizationSetBy = Automatic

	column hire_date
		dataType: string
		lineageTag: 3e79650f-6300-4799-bb54-cbcbbc846777
		summarizeBy: none
		sourceColumn: hire_date

		annotation SummarizationSetBy = Automatic

	column option_id
		dataType: string
		lineageTag: 2825a0e9-4eda-4fb7-b4ab-4cd3c91668f0
		summarizeBy: none
		sourceColumn: option_id

		annotation SummarizationSetBy = Automatic

	column incentive_indicator
		dataType: string
		lineageTag: 8f3ae417-1041-4c4f-b9b8-23f47a98b068
		summarizeBy: none
		sourceColumn: incentive_indicator

		annotation SummarizationSetBy = Automatic

	column group_code
		dataType: string
		lineageTag: 0f849b82-ae56-4df8-b237-3642e881b616
		summarizeBy: none
		sourceColumn: group_code

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_1
		dataType: string
		lineageTag: 87c73f01-e5c2-487f-8551-a6f7b6c2f944
		summarizeBy: none
		sourceColumn: custom_defined_field_1

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_2
		dataType: string
		lineageTag: 1feb686a-c97d-4104-adef-7959f5174773
		summarizeBy: none
		sourceColumn: custom_defined_field_2

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_3
		dataType: string
		lineageTag: 176684be-0006-460b-9893-c9cf71e967cf
		summarizeBy: none
		sourceColumn: custom_defined_field_3

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_4
		dataType: string
		lineageTag: 5007d596-6b18-4f76-a31f-857cee33aee7
		summarizeBy: none
		sourceColumn: custom_defined_field_4

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_5
		dataType: string
		lineageTag: 20fb7153-f4c3-4b43-af23-c98e0805accd
		summarizeBy: none
		sourceColumn: custom_defined_field_5

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_6
		dataType: string
		lineageTag: 82243a3d-3d8c-4712-a76f-aaeb63c7cc58
		summarizeBy: none
		sourceColumn: custom_defined_field_6

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_7
		dataType: string
		lineageTag: 3116a40a-d580-4282-be32-03e40c19a174
		summarizeBy: none
		sourceColumn: custom_defined_field_7

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_8
		dataType: string
		lineageTag: 1e587bf3-310e-4b84-946c-8fadb44d20bb
		summarizeBy: none
		sourceColumn: custom_defined_field_8

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_9
		dataType: string
		lineageTag: 33c08582-a7f4-41c6-a4c3-9ecb41ebe049
		summarizeBy: none
		sourceColumn: custom_defined_field_9

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_10
		dataType: string
		lineageTag: 1baa8044-32f3-4372-ab6d-99cf66fd0ce7
		summarizeBy: none
		sourceColumn: custom_defined_field_10

		annotation SummarizationSetBy = Automatic

	column suffix
		dataType: string
		lineageTag: 1d341bf0-5a3c-4b1f-995d-e8af229fd73a
		summarizeBy: none
		sourceColumn: suffix

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 800d5589-6523-4b77-9f11-34cc9e0689c7
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column latest_date
		dataType: string
		lineageTag: 7e09e861-55c2-4f4b-b954-87c5876eb07c
		summarizeBy: none
		sourceColumn: latest_date

		annotation SummarizationSetBy = Automatic

	column org_id
		dataType: int64
		formatString: 0
		lineageTag: 581c3765-c837-4e95-98a9-e3793333ecb5
		summarizeBy: sum
		sourceColumn: org_id

		annotation SummarizationSetBy = Automatic

	column Client_id_name
		dataType: string
		lineageTag: 7037ec96-2ca2-4459-b64f-4bae3ff5406d
		summarizeBy: none
		sourceColumn: Client_id_name

		annotation SummarizationSetBy = Automatic

	column NewEmailColumn = ```
			
			SWITCH(
			    TRUE(),
			    'member_dimension'[client_id] = "0708130" && 'member_dimension'[org_id] = 4000084, "pramit.kundu@capillary365.onmicrosoft.com",
			    'member_dimension'[client_id] = "0914680" && 'member_dimension'[org_id] = 4000095, "arnika.jain@capillary365.onmicrosoft.com",
			    "saakshi.mankar@capillarytech.com"  // default email if client_id/org_id does not match any
			)
			
			```
		lineageTag: af363893-9843-43c9-b679-4aac502bcf2f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition member_dimension = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("capillary-notebook-ushc.cloud.databricks.com", "sql/protocolv1/o/3729305870030/0813-073652-brrb0l8n", null),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    optum_dev_Schema = hive_metastore_Database{[Name=SchemaName,Kind="Schema"]}[Data],
				    member_dimension_Table = optum_dev_Schema{[Name="member_dimension",Kind="Table"]}[Data],
				    #"Added Custom" = Table.AddColumn(member_dimension_Table, "Custom", each [client_id] & " " & [client_name]),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each true),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Custom", "Client_id_name"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"join_date", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"join_date", type date}, {"start_date", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

