table member_dimension
	lineageTag: 40f39411-4646-4c19-8dd3-28cebf52f398

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: be0099b3-8568-4fb0-8b63-72987dfbd834
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: string
		lineageTag: 08cfa331-c9c3-4fe5-8172-402c63f4dcba
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: string
		lineageTag: c021eef7-63ba-47ff-98f0-c0d84c0fe2d0
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 8bab109c-241e-4060-926f-e348bfb0834a
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column terms_and_conditions_acceptance_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4c3c1cfb-6e1c-4ee3-973d-47214d0500b4
		summarizeBy: none
		sourceColumn: terms_and_conditions_acceptance_date

		variation Variation
			isDefault
			relationship: e82ac048-0757-47c4-a96e-d9fb517cc7ab
			defaultHierarchy: LocalDateTable_b097889f-771b-4b3b-88bc-0ede8a3d2d19.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column screenname
		dataType: string
		lineageTag: be791502-a7df-4f78-a0bd-b84e8523503e
		summarizeBy: none
		sourceColumn: screenname

		annotation SummarizationSetBy = Automatic

	column date_of_birth
		dataType: string
		lineageTag: 0e1b2890-07c4-4428-85e1-1070e6dcc2d4
		summarizeBy: none
		sourceColumn: date_of_birth

		annotation SummarizationSetBy = Automatic

	column join_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: adb723f6-32a2-4b3d-9c2f-a313b08d2800
		summarizeBy: none
		sourceColumn: join_date

		variation Variation
			isDefault
			relationship: 7b7e7aed-6251-4f63-abe3-6c6a4488006e
			defaultHierarchy: LocalDateTable_892887c7-de91-44d0-824d-dbddbeee5a6a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column efid
		dataType: string
		lineageTag: 4ca73a9d-7072-43cb-8ec6-774ca9c5d144
		summarizeBy: none
		sourceColumn: efid

		annotation SummarizationSetBy = Automatic

	column vendor_id
		dataType: string
		lineageTag: f9db0179-ae43-471e-a228-5b95311e80d8
		summarizeBy: none
		sourceColumn: vendor_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 529ab85f-913a-47c4-a4b8-5b295b6675ca
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: c960d7e8-736b-447a-bfce-66025323a639
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column mobile_phone_number
		dataType: string
		lineageTag: 586f2065-8af1-4631-8bca-bc10806bb52f
		summarizeBy: none
		sourceColumn: mobile_phone_number

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 3aaf6949-7674-43ce-bd1c-40f3698fa9e0
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column middle_name
		dataType: string
		lineageTag: ece075dd-abea-4f9e-95fe-4921a7faad1a
		summarizeBy: none
		sourceColumn: middle_name

		annotation SummarizationSetBy = Automatic

	column division_name
		dataType: string
		lineageTag: 7b027420-acf7-4db3-bb96-e0df960a81db
		summarizeBy: none
		sourceColumn: division_name

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: 9ddb1261-10df-45fe-a6c8-fffd2efce1b8
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column source_system_code
		dataType: string
		lineageTag: 8d7ecf01-1e5b-48f2-b59a-92495314e870
		summarizeBy: none
		sourceColumn: source_system_code

		annotation SummarizationSetBy = Automatic

	column funding_arrangement_code
		dataType: string
		lineageTag: 223b579f-00ed-46b5-b2a3-76a415c11360
		summarizeBy: none
		sourceColumn: funding_arrangement_code

		annotation SummarizationSetBy = Automatic

	column health_plan_product_code
		dataType: string
		lineageTag: 0d9847d1-6f5b-4676-a531-4046662ef226
		summarizeBy: none
		sourceColumn: health_plan_product_code

		annotation SummarizationSetBy = Automatic

	column legal_entity_code
		dataType: string
		lineageTag: b3870f14-a050-4ace-96a4-f0dc996c63f8
		summarizeBy: none
		sourceColumn: legal_entity_code

		annotation SummarizationSetBy = Automatic

	column line_of_business
		dataType: string
		lineageTag: e48a50f7-5edf-4320-bf2c-71169f32545c
		summarizeBy: none
		sourceColumn: line_of_business

		annotation SummarizationSetBy = Automatic

	column member_effective_date
		dataType: string
		lineageTag: 1d0c1719-f24d-429a-b95a-f44abb6ddb2a
		summarizeBy: none
		sourceColumn: member_effective_date

		annotation SummarizationSetBy = Automatic

	column member_termination_date
		dataType: string
		lineageTag: 06427ad9-457f-400d-8eae-2960322a2003
		summarizeBy: none
		sourceColumn: member_termination_date

		annotation SummarizationSetBy = Automatic

	column medical_coverage
		dataType: string
		lineageTag: 7535888f-af6e-4b18-8bca-8852575227f9
		summarizeBy: none
		sourceColumn: medical_coverage

		annotation SummarizationSetBy = Automatic

	column medical_plan_organization_id
		dataType: string
		lineageTag: 12a07e8f-296d-4849-9961-69cfa059b68c
		summarizeBy: none
		sourceColumn: medical_plan_organization_id

		annotation SummarizationSetBy = Automatic

	column market_segment_name
		dataType: string
		lineageTag: 2f5b7bb6-72df-45da-9c39-402242720dc6
		summarizeBy: none
		sourceColumn: market_segment_name

		annotation SummarizationSetBy = Automatic

	column marital_status
		dataType: string
		lineageTag: b34c756a-42b1-4dc3-92f0-3aca77513369
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column group_policy_number
		dataType: string
		lineageTag: 5900e18f-ba99-4bca-ba20-e6fbe405d99d
		summarizeBy: none
		sourceColumn: group_policy_number

		annotation SummarizationSetBy = Automatic

	column purchaser_code
		dataType: string
		lineageTag: 4a3604ec-067c-4429-8681-50353656e66d
		summarizeBy: none
		sourceColumn: purchaser_code

		annotation SummarizationSetBy = Automatic

	column plan_variation_and_branch_reporting_code
		dataType: string
		lineageTag: 10440744-37ce-4f78-9690-85d486b991da
		summarizeBy: none
		sourceColumn: plan_variation_and_branch_reporting_code

		annotation SummarizationSetBy = Automatic

	column retirement_plan_text
		dataType: string
		lineageTag: 8dfbcc22-9447-43f6-ba0a-504779860852
		summarizeBy: none
		sourceColumn: retirement_plan_text

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 6bdd2d99-c299-46d2-a6cc-f530d6782661
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column union_status
		dataType: string
		lineageTag: eddbfd5f-4aa2-4241-bf4f-cabdc5bf562d
		summarizeBy: none
		sourceColumn: union_status

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: e397b8b5-78b9-427b-bc5f-28a9ab95f077
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column work_location_name
		dataType: string
		lineageTag: ce9d9ac1-b41a-463e-bad2-db848f777223
		summarizeBy: none
		sourceColumn: work_location_name

		annotation SummarizationSetBy = Automatic

	column population_id
		dataType: string
		lineageTag: 8ba744c6-9a8a-4322-bc2a-b997fac509cd
		summarizeBy: none
		sourceColumn: population_id

		annotation SummarizationSetBy = Automatic

	column insurance_issuance_state_code
		dataType: string
		lineageTag: d00d481d-cf49-4675-8448-71722612fa53
		summarizeBy: none
		sourceColumn: insurance_issuance_state_code

		annotation SummarizationSetBy = Automatic

	column partner_name
		dataType: string
		lineageTag: 6bc44aa3-2c53-498e-9618-4d2ce3fb259d
		summarizeBy: none
		sourceColumn: partner_name

		annotation SummarizationSetBy = Automatic

	column relationship_code
		dataType: string
		lineageTag: 1b9680f2-e4d8-42c0-a015-44e9a770fdd9
		summarizeBy: none
		sourceColumn: relationship_code

		annotation SummarizationSetBy = Automatic

	column spee_indicator
		dataType: string
		lineageTag: ff7cc527-f896-4527-8e19-2ab3940fb54d
		summarizeBy: none
		sourceColumn: spee_indicator

		annotation SummarizationSetBy = Automatic

	column partner_id
		dataType: string
		lineageTag: 31d91b1d-0363-4ecf-8f28-0699883ce450
		summarizeBy: none
		sourceColumn: partner_id

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: e6574991-b1c1-4201-848c-d4ab4c18008a
		summarizeBy: none
		sourceColumn: postal_code

		annotation SummarizationSetBy = Automatic

	column employee_id
		dataType: string
		lineageTag: 695db7bb-6eec-4b1b-b135-da5ae9cb98af
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column client
		dataType: string
		lineageTag: 61d07425-f3fe-41c0-aee9-fef14dfe1f0c
		summarizeBy: none
		sourceColumn: client

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: string
		lineageTag: b5b9cb2d-a8da-40dd-915e-75c62177cdea
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column client_name
		dataType: string
		lineageTag: 77f7dc6b-2152-4aca-b99d-355dfe52beb6
		summarizeBy: none
		sourceColumn: client_name

		annotation SummarizationSetBy = Automatic

	column affiliation_id
		dataType: string
		lineageTag: 088bfcce-8c5b-400f-b9cd-8a682fa92e58
		summarizeBy: none
		sourceColumn: affiliation_id

		annotation SummarizationSetBy = Automatic

	column affiliation_description
		dataType: string
		lineageTag: 62100a27-ceab-4954-a75c-b1685525412e
		summarizeBy: none
		sourceColumn: affiliation_description

		annotation SummarizationSetBy = Automatic

	column address_line_1
		dataType: string
		lineageTag: 769f3f13-9cda-48a4-aa44-b490ee0ecc51
		summarizeBy: none
		sourceColumn: address_line_1

		annotation SummarizationSetBy = Automatic

	column address_line_2
		dataType: string
		lineageTag: 4912235c-6e98-4aba-a3f4-0110395bd776
		summarizeBy: none
		sourceColumn: address_line_2

		annotation SummarizationSetBy = Automatic

	column alternate_id
		dataType: string
		lineageTag: f0f2bbea-fa33-44af-b3f6-80f4a6ae0dbe
		summarizeBy: none
		sourceColumn: alternate_id

		annotation SummarizationSetBy = Automatic

	column cobra_text
		dataType: string
		lineageTag: 61ea4b4b-8501-4966-9721-4ff9290598b2
		summarizeBy: none
		sourceColumn: cobra_text

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: e37a8795-5b21-404c-9686-13102167b1fa
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column salary_hourly_indicator
		dataType: string
		lineageTag: 29952ed4-c40d-4404-aef2-9b3c1e85b3fc
		summarizeBy: none
		sourceColumn: salary_hourly_indicator

		annotation SummarizationSetBy = Automatic

	column new_hire_indicator
		dataType: string
		lineageTag: ac591d35-22ba-4e5a-b1f5-e8618936d023
		summarizeBy: none
		sourceColumn: new_hire_indicator

		annotation SummarizationSetBy = Automatic

	column hire_date
		dataType: string
		lineageTag: b1e4f73c-2343-441c-ad88-600da3b7782e
		summarizeBy: none
		sourceColumn: hire_date

		annotation SummarizationSetBy = Automatic

	column option_id
		dataType: string
		lineageTag: 39d2d3d5-08bb-4ec1-84ba-c73acf894423
		summarizeBy: none
		sourceColumn: option_id

		annotation SummarizationSetBy = Automatic

	column incentive_indicator
		dataType: string
		lineageTag: 7836a7bf-519a-4b8c-a0b2-5ae80e219f53
		summarizeBy: none
		sourceColumn: incentive_indicator

		annotation SummarizationSetBy = Automatic

	column group_code
		dataType: string
		lineageTag: 541142f3-6a8a-4131-b59f-6d031850fd33
		summarizeBy: none
		sourceColumn: group_code

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_1
		dataType: string
		lineageTag: 0e9cb77b-387c-4920-b004-cc0b4ae93e07
		summarizeBy: none
		sourceColumn: custom_defined_field_1

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_2
		dataType: string
		lineageTag: ff539086-bee6-467f-abbc-9b1cb9ba12d7
		summarizeBy: none
		sourceColumn: custom_defined_field_2

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_3
		dataType: string
		lineageTag: 5184557f-7b9c-4c74-a2c9-785faf9871e4
		summarizeBy: none
		sourceColumn: custom_defined_field_3

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_4
		dataType: string
		lineageTag: 275a3949-95cd-4a4e-b93b-be4df46eb49e
		summarizeBy: none
		sourceColumn: custom_defined_field_4

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_5
		dataType: string
		lineageTag: a2ddd702-0332-4c4a-9b74-2a41200dfb19
		summarizeBy: none
		sourceColumn: custom_defined_field_5

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_6
		dataType: string
		lineageTag: 8529f0c7-3963-4197-847e-e979e0f99884
		summarizeBy: none
		sourceColumn: custom_defined_field_6

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_7
		dataType: string
		lineageTag: 8ba47280-f4e3-43dd-b488-d031d9c4ef09
		summarizeBy: none
		sourceColumn: custom_defined_field_7

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_8
		dataType: string
		lineageTag: f2b5b79d-1971-4975-bc4d-8dd96550cb87
		summarizeBy: none
		sourceColumn: custom_defined_field_8

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_9
		dataType: string
		lineageTag: a534e1e1-8062-4f29-9640-b788777d9b1a
		summarizeBy: none
		sourceColumn: custom_defined_field_9

		annotation SummarizationSetBy = Automatic

	column custom_defined_field_10
		dataType: string
		lineageTag: 559c5ea7-98eb-4969-bac3-d4c9f09569b9
		summarizeBy: none
		sourceColumn: custom_defined_field_10

		annotation SummarizationSetBy = Automatic

	column suffix
		dataType: string
		lineageTag: 34da0de3-42c5-4adc-9bbd-f0e3f76355c2
		summarizeBy: none
		sourceColumn: suffix

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 136aa7b3-0ad5-415d-b787-af5289fca28c
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column latest_date
		dataType: string
		lineageTag: da2a947f-d337-412a-94ce-d36341a6209e
		summarizeBy: none
		sourceColumn: latest_date

		annotation SummarizationSetBy = Automatic

	column org_id
		dataType: int64
		formatString: 0
		lineageTag: 43a21fe5-e0a4-4d4e-b15e-eddcbf6777f9
		summarizeBy: sum
		sourceColumn: org_id

		annotation SummarizationSetBy = Automatic

	column Client_id_name
		dataType: string
		lineageTag: 84feb9a5-ed21-433b-a10c-c7928ecdc048
		summarizeBy: none
		sourceColumn: Client_id_name

		annotation SummarizationSetBy = Automatic

	partition member_dimension = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("capillary-notebook-ushc.cloud.databricks.com", "sql/protocolv1/o/3729305870030/0813-073652-brrb0l8n", null),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    optum_dev_Schema = hive_metastore_Database{[Name=SchemaName,Kind="Schema"]}[Data],
				    member_dimension_Table = optum_dev_Schema{[Name="member_dimension",Kind="Table"]}[Data],
				    #"Added Custom" = Table.AddColumn(member_dimension_Table, "Client_id_name", each [client_id] & " " & [client_name]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Client_id_name", type text}, {"terms_and_conditions_acceptance_date", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"terms_and_conditions_acceptance_date", type date}, {"join_date", type datetime}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"join_date", type date}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

